# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: msakurad <msakurad@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/05/04 17:25:54 by msakurad          #+#    #+#              #
#    Updated: 2023/05/05 14:32:23 by msakurad         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME: libft.a
SRC: \
	ft_isalnum.c ft_isalpha.c ft_isascii.c ft_isdigit.c ft_isprint.c

OBJ: 

CCFLAGS: -Wall -Wextra -Werror

all: $(NAME)

$(NAME):
	cc $(CCFLAGS) 

clean:
	rm -f *.o

fclean: clean
	rm -f *.a

bonus: